sudo: required
services:
  - docker
language: java
jdk:
  - oraclejdk8
#before_install:
  #- sudo apt-get install linux-headers-`uname -r`
  #- sudo apt-get install virtualbox
  #- wget https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4_x86_64.deb
  #- sudo dpkg -i vagrant_1.8.4_x86_64.deb
script:
  - cd sleuth-documentation-apps && ./gradlew clean build --parallel
env:
  global:
  - TERM=dumb
